version: '3.8'
services:
  api:
    build: './api'
    ports:
      - "3000:3000"
    depends_on: 
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: dockuser
      DB_DATABASE: dock
      DB_PASSWORD: passw0rd1234
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dockuser
      POSTGRES_PASSWORD: passw0rd1234
      POSTGRES_DB: dock
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: {}